### ISSUE TITLE
Creates an anti spam log even though there is one

### ISSUE THREAD

**Issue by Jaxenormus** [MirageZoe/better-discord-antispam#1]
My bot creates an anti-spam log every time someone spams even though there is already one created, it also dm's me saying that it wasn't able to mute them but they did

**Comment by MirageZoe** [comment]
Hello @CalebDelbridge ,

Can I see your code and also an image of the duplicated channels (+ dm's) from discord?
I need more information first in order to create a fix and to make sure I got everything alright:

- your bot creates a log channel everytime someone spam (so if they spammed 100 times, 100 channels are created right?
- it dm you that he couldn't mute someone but they got muted right?

**Comment by Jaxenormus** [comment]
Yep its creates a log every time someone spams and yes it does dm when that he couldn't mute but they got muted and the code is nothing but the default code that you provided

**Comment by MirageZoe** [comment]
Ah, sorry for not saying more detailed. Please give me the configuration you set for the module. It should be something like this:

```
const antispam = require("");

//some code here


> 
> antispam(client, {
>         limitUntilWarn: 3, // The amount of messages allowed to send within the interval(time) before getting a warn.
>         limitUntilMuted: 5, // The amount of messages allowed to send within the interval(time) before getting a muted.
>         interval: 2000, // The interval(time) where the messages are sent. Practically if member X sent 5+ messages within 2 seconds, he get muted. (1000 milliseconds = 1 second, 2000 milliseconds = 2 seconds etc etc)
>         warningMessage: "if you don't stop from spamming, I'm going to punish you!", // Message you get when you are warned!
>         muteMessage: "was muted since we don't like too much advertisement type people!", // Message sent after member X was punished(muted).
>         maxDuplicatesWarning: 7,// When people are spamming the same message, this will trigger when member X sent over 7+ messages.
>         maxDuplicatesMute: 10, // The limit where member X get muted after sending too many messages(10+).
>         ignoredRoles: ["Admin"], // The members with this role(or roles) will be ignored if they have it. Suggest to not add this to any random guys. Also it's case sensitive.
>         ignoredMembers: ["SomeUser#1111"], // These members are directly affected and they do not require to have the role above. Good for undercover pranks.
> 		mutedRole: "muted", // Here you put the name of the role that should not let people write/speak or anything else in your server. If there is no role set, by default, the module will attempt to create the role for you & set it correctly for every channel in your server. It will be named "muted".
> 		timeMuted: 1000 * 600, // This is how much time member X will be muted. if not set, default would be 10 min.
> 		logChannel: "antiSpam-logs" // This is the channel where every report about spamming goes to. If it's not set up, it will attempt to create the channel.
>       });
```


so based on what you said, it seems like it's a little mistake in the "logChannel" property. Make sure the name doesn't start with a Capital letter (if your log channel is **AntiSpam-logs** or it has any capital letter in it , make sure to be **antispam-logs** because discord for some reasons doesn't let you create channels with capital letters in the name). About the mute thing, who tried to mute ? 
Also like I said, if possible please send some pics or a video on how it does. without the settings you did or anything else, it's not too much info to understand where the actual problem is.

**Comment by Jaxenormus** [comment]
Seem to be working now and logging everything correctly, whatever you did it worked. Cheers

**Comment by MirageZoe** [comment]
Okay then I'm happy that fixed everything. Now going to close the ticket. Have a nice day
