### ISSUE TITLE
Yo do you know embed.setTimestamp() is a thing?

### ISSUE THREAD

**Issue by xShadoww** [MirageZoe/better-discord-antispam#5]
You have so much complicated code to create a timestamp for no reason lol

**Comment by MirageZoe** [comment]
Yes, I know **embed.setTimestamp()** is a thing in **MessageEmbed()** (previously known as _RichEmbed_) because I'm working with it for at least 1 year+. Now regarding your remark about "

> _complicating my code **so much** for no reason_

"
Well, I don't like it to be shown down below and gray! Also you don't have to use it at all since discord already have a timestamp for the message itself so there is no need to look at my custom timestamp code if you don't feel like. I just wanted to create timestamp that I could manipulate anytime I wanted and take exactly what I wanted. If you try to use it (_setTimestamp()_), you cannot put anywhere else except the bottom side of the embed. _(Also gives error when u try to use something like: .addfield(`Time: `, embed.setTimestamp())_

Thank you very much for caring!
